name: flutter_sound_web
version: 6.0.1
description: Flutter plugin that relates to sound like audio and recorder.
#author: dooboolab<dooboolab@gmail.com>
homepage: https://github.com/dooboolab/flutter_sound
# 0.1.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterSoundWeb
        fileName: flutter_sound_web.dart

dependencies:
  url_launcher_platform_interface: ^1.0.8
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^5.2.5
  pedantic: ^1.8.0
  mockito: ^4.1.1
  integration_test:
    path: ../../integration_test

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"